// <auto-generated />
using System;
using CartonCaps.Referrals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartonCaps.Referrals.Data.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    partial class ReferralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CartonCaps.Referrals.Data.Models.Referral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReferredOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReferredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReferrerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Referrals");
                });
#pragma warning restore 612, 618
        }
    }
}
